// Generated by LiveScript 1.2.0
(function(){
  var fs, csv, records, c, this$ = this;
  fs = require('fs');
  csv = require('csv');
  records = [];
  c = csv().from.stream(fs.createReadStream(__dirname + "/data/rozpocet14Vydaje.txt")).on('record', function(arg$){
    var kapitola, financni_misto, akce, rozpoctova_polozka, castka;
    kapitola = arg$[0], financni_misto = arg$[1], akce = arg$[2], rozpoctova_polozka = arg$[3], castka = arg$[4];
    return kapitola === 'kapitola';
    return records.push({
      kapitola: kapitola,
      financni_misto: financni_misto,
      akce: akce,
      rozpoctova_polozka: rozpoctova_polozka,
      castka: castka
    });
  });
  c.on('end', function(){
    return console.log(records.length);
  });
}).call(this);
